"""edit BookModel

Revision ID: 6454aedf869c
Revises: 8b3fadb1d117
Create Date: 2026-07-17 18:27:37.907358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6454aedf869c'
down_revision: Union[str, Sequence[str], None] = '8b3fadb1d117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('annotation', sa.String(), nullable=False))
    op.add_column('books', sa.Column('genre', sa.String(), nullable=False))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'genre')
    op.drop_column('books', 'annotation')
    # ### end Alembic commands ###
